FROM node:16-alpine

WORKDIR /app

COPY package.json .
RUN npm install

#A fix for EACCESS
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

CMD ["npm", "run", "start"]

# in order to make sure to build using this docker file use 'docker build -f Dockerfile.dev .'